services:
  postgres:
    image: postgres:16-alpine
    container_name: cb-sau-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cibershield_sau
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cibershield_sau"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
